theme = "solarized-dark"

[icons]
name = "awesome"
[icons.overrides]
bat_charging = "  "
bat_discharging = "  "
bat_full = "  "
cogs = "LOAD "
cpu = "CPU "
memory_mem = "MEM "
music = "  "

#[[block]]
#block = "music"
#player = "spotify"
#max_width = 40
#marquee = false

[[block]]
block = "sound"
interval = 1

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GiB"
interval = 20

[[block]]
block = "disk_space"
path = "/home/"
alias = "/home"
info_type = "available"
unit = "GiB"
interval = 20

[[block]]
block = "net"
device = "enp0s20u1"
ip = true
speed_up = false
speed_down = false

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
bitrate = true
ip = true
speed_up = false
speed_down = false

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug} GiB"
clickable = false

[[block]]
block = "battery"
interval = 5

[[block]]
block = "time"
interval = 20
format = " %d.%m.%Y %R"
