theme = "solarized-dark"
#icons = "awesome"

[[block]]
block = "sound"
interval = 1

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GiB"
interval = 20

[[block]]
block = "disk_space"
path = "/home/"
alias = "/home"
info_type = "available"
unit = "GiB"
interval = 20

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
clickable = false

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "battery"
interval = 5

[[block]]
block = "time"
interval = 30
format = "%d.%m.%Y %R"
