# base16_aterlier-dune
[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#20201d"
idle_fg = "#a6a28c"
info_bg = "#1fad83"
info_fg = "#20201d"
good_bg = "#60ac39"
good_fg = "#20201d"
warning_bg = "#ae9513"
warning_fg = "#20201d"
critical_bg = "#d73737"
critical_fg = "#20201d"
# The rest of the theme settings are left at default.

[icons]
name = "awesome"
[icons.overrides]
bat_charging = "  "
bat_discharging = "  "
bat_full = "  "
cogs = "LOAD "
cpu = "CPU "
memory_mem = "MEM "
music = "   "

#[[block]]
#block = "music"
#player = "spotify"
#max_width = 50
#marquee = false

[[block]]
block = "sound"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GiB"
interval = 20

[[block]]
block = "disk_space"
path = "/home/"
alias = "/home"
info_type = "available"
unit = "GiB"
interval = 20

#[[block]]
#block = "net"
#device = "enp0s20u1"
#ip = true
#speed_up = false
#speed_down = false

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
bitrate = true
ip = true
speed_up = false
speed_down = false

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug} GiB"
clickable = false

[[block]]
block = "battery"
interval = 5
upower = true
#format = "{percentage}% [{time}]"

[[block]]
block = "time"
interval = 20
format = " %d.%m.%Y %R"
